/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OauthConsentRouteImport } from "./routes/oauth.consent";
import { Route as AuthenticatedSkillsRouteImport } from "./routes/_authenticated/skills";
import { Route as AuthenticatedSkillsIndexRouteImport } from "./routes/_authenticated/skills.index";
import { Route as AuthenticatedSkillsNewRouteImport } from "./routes/_authenticated/skills.new";
import { Route as AuthenticatedSkillsForkRouteImport } from "./routes/_authenticated/skills.fork";
import { Route as AuthenticatedSkillsSkillIdRouteImport } from "./routes/_authenticated/skills.$skillId";
import { Route as AuthenticatedSkillsSkillIdEditRouteImport } from "./routes/_authenticated/skills.$skillId.edit";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: "/oauth/consent",
  path: "/oauth/consent",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedSkillsRoute,
  } as any);
const AuthenticatedSkillsNewRoute = AuthenticatedSkillsNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AuthenticatedSkillsRoute,
} as any);
const AuthenticatedSkillsForkRoute = AuthenticatedSkillsForkRouteImport.update({
  id: "/fork",
  path: "/fork",
  getParentRoute: () => AuthenticatedSkillsRoute,
} as any);
const AuthenticatedSkillsSkillIdRoute =
  AuthenticatedSkillsSkillIdRouteImport.update({
    id: "/$skillId",
    path: "/$skillId",
    getParentRoute: () => AuthenticatedSkillsRoute,
  } as any);
const AuthenticatedSkillsSkillIdEditRoute =
  AuthenticatedSkillsSkillIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => AuthenticatedSkillsSkillIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/skills": typeof AuthenticatedSkillsRouteWithChildren;
  "/oauth/consent": typeof OauthConsentRoute;
  "/skills/$skillId": typeof AuthenticatedSkillsSkillIdRouteWithChildren;
  "/skills/fork": typeof AuthenticatedSkillsForkRoute;
  "/skills/new": typeof AuthenticatedSkillsNewRoute;
  "/skills/": typeof AuthenticatedSkillsIndexRoute;
  "/skills/$skillId/edit": typeof AuthenticatedSkillsSkillIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/oauth/consent": typeof OauthConsentRoute;
  "/skills/$skillId": typeof AuthenticatedSkillsSkillIdRouteWithChildren;
  "/skills/fork": typeof AuthenticatedSkillsForkRoute;
  "/skills/new": typeof AuthenticatedSkillsNewRoute;
  "/skills": typeof AuthenticatedSkillsIndexRoute;
  "/skills/$skillId/edit": typeof AuthenticatedSkillsSkillIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/skills": typeof AuthenticatedSkillsRouteWithChildren;
  "/oauth/consent": typeof OauthConsentRoute;
  "/_authenticated/skills/$skillId": typeof AuthenticatedSkillsSkillIdRouteWithChildren;
  "/_authenticated/skills/fork": typeof AuthenticatedSkillsForkRoute;
  "/_authenticated/skills/new": typeof AuthenticatedSkillsNewRoute;
  "/_authenticated/skills/": typeof AuthenticatedSkillsIndexRoute;
  "/_authenticated/skills/$skillId/edit": typeof AuthenticatedSkillsSkillIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/skills"
    | "/oauth/consent"
    | "/skills/$skillId"
    | "/skills/fork"
    | "/skills/new"
    | "/skills/"
    | "/skills/$skillId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/oauth/consent"
    | "/skills/$skillId"
    | "/skills/fork"
    | "/skills/new"
    | "/skills"
    | "/skills/$skillId/edit";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/skills"
    | "/oauth/consent"
    | "/_authenticated/skills/$skillId"
    | "/_authenticated/skills/fork"
    | "/_authenticated/skills/new"
    | "/_authenticated/skills/"
    | "/_authenticated/skills/$skillId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  OauthConsentRoute: typeof OauthConsentRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/oauth/consent": {
      id: "/oauth/consent";
      path: "/oauth/consent";
      fullPath: "/oauth/consent";
      preLoaderRoute: typeof OauthConsentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/skills": {
      id: "/_authenticated/skills";
      path: "/skills";
      fullPath: "/skills";
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/skills/": {
      id: "/_authenticated/skills/";
      path: "/";
      fullPath: "/skills/";
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport;
      parentRoute: typeof AuthenticatedSkillsRoute;
    };
    "/_authenticated/skills/new": {
      id: "/_authenticated/skills/new";
      path: "/new";
      fullPath: "/skills/new";
      preLoaderRoute: typeof AuthenticatedSkillsNewRouteImport;
      parentRoute: typeof AuthenticatedSkillsRoute;
    };
    "/_authenticated/skills/fork": {
      id: "/_authenticated/skills/fork";
      path: "/fork";
      fullPath: "/skills/fork";
      preLoaderRoute: typeof AuthenticatedSkillsForkRouteImport;
      parentRoute: typeof AuthenticatedSkillsRoute;
    };
    "/_authenticated/skills/$skillId": {
      id: "/_authenticated/skills/$skillId";
      path: "/$skillId";
      fullPath: "/skills/$skillId";
      preLoaderRoute: typeof AuthenticatedSkillsSkillIdRouteImport;
      parentRoute: typeof AuthenticatedSkillsRoute;
    };
    "/_authenticated/skills/$skillId/edit": {
      id: "/_authenticated/skills/$skillId/edit";
      path: "/edit";
      fullPath: "/skills/$skillId/edit";
      preLoaderRoute: typeof AuthenticatedSkillsSkillIdEditRouteImport;
      parentRoute: typeof AuthenticatedSkillsSkillIdRoute;
    };
  }
}

interface AuthenticatedSkillsSkillIdRouteChildren {
  AuthenticatedSkillsSkillIdEditRoute: typeof AuthenticatedSkillsSkillIdEditRoute;
}

const AuthenticatedSkillsSkillIdRouteChildren: AuthenticatedSkillsSkillIdRouteChildren =
  {
    AuthenticatedSkillsSkillIdEditRoute: AuthenticatedSkillsSkillIdEditRoute,
  };

const AuthenticatedSkillsSkillIdRouteWithChildren =
  AuthenticatedSkillsSkillIdRoute._addFileChildren(
    AuthenticatedSkillsSkillIdRouteChildren,
  );

interface AuthenticatedSkillsRouteChildren {
  AuthenticatedSkillsSkillIdRoute: typeof AuthenticatedSkillsSkillIdRouteWithChildren;
  AuthenticatedSkillsForkRoute: typeof AuthenticatedSkillsForkRoute;
  AuthenticatedSkillsNewRoute: typeof AuthenticatedSkillsNewRoute;
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute;
}

const AuthenticatedSkillsRouteChildren: AuthenticatedSkillsRouteChildren = {
  AuthenticatedSkillsSkillIdRoute: AuthenticatedSkillsSkillIdRouteWithChildren,
  AuthenticatedSkillsForkRoute: AuthenticatedSkillsForkRoute,
  AuthenticatedSkillsNewRoute: AuthenticatedSkillsNewRoute,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
};

const AuthenticatedSkillsRouteWithChildren =
  AuthenticatedSkillsRoute._addFileChildren(AuthenticatedSkillsRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSkillsRoute: AuthenticatedSkillsRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthConsentRoute: OauthConsentRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
